package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"encoding/base64"
	"errors"
	"fmt"
	"jwt_go/graph/helpers"
	"jwt_go/graph/model"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/crypto/bcrypt"
	"gorm.io/gorm"
)

// Register handles user registration
func (r *mutationResolver) Register(ctx context.Context, name string, username string, email *string, password string) (*model.AuthResponse, error) {
	log.Println("Registering new user...")

	// Ensure username is unique
	var existing model.UserDB
	if err := r.DB.Where("username = ?", username).First(&existing).Error; err == nil {
		return nil, errors.New("username already in use")
	} else if !errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, fmt.Errorf("error checking username: %v", err)
	}
	// Ensure email (if provided) is unique
	if email != nil && *email != "" {
		var byEmail model.UserDB
		if err := r.DB.Where("email = ?", *email).First(&byEmail).Error; err == nil {
			return nil, errors.New("email already in use")
		} else if !errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("error checking email: %v", err)
		}
	}

	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("error hashing password: %v", err)
	}

	// Create new user
	user := model.UserDB{
		Name:     name,
		Username: username,
		Password: string(hashedPassword),
		IsActive: true,
	}
	if email != nil {
		user.Email = *email
	}

	if err := r.DB.Create(&user).Error; err != nil {
		log.Printf("register: DB create error: %v", err)
		return nil, err
	}

	token, err := generateJWT(int32(user.ID), user.Username)
	if err != nil {
		log.Printf("register: token generation failed: %v", err)
		return nil, errors.New("failed to generate token")
	}

	// Convert to GraphQL model
	userModel := toGraphQLUser(user)

	return &model.AuthResponse{
		Token: token,
		User:  userModel,
	}, nil
}

// Login handles user login and returns a JWT token
func (r *mutationResolver) Login(ctx context.Context, username string, password string) (*model.AuthResponse, error) {
	// Find user by username
	var user model.UserDB
	if err := r.DB.Where("username = ?", username).First(&user).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, errors.New("invalid username or password")
		}
		return nil, fmt.Errorf("error finding user: %v", err)
	}

	// Check password
	if err := bcrypt.CompareHashAndPassword([]byte(user.Password), []byte(password)); err != nil {
		return nil, errors.New("invalid username or password")
	}

	// Generate JWT token
	token, err := generateJWT(int32(user.ID), user.Username)
	if err != nil {
		return nil, errors.New("failed to generate token")
	}

	// Convert to GraphQL model
	userModel := toGraphQLUser(user)

	return &model.AuthResponse{
		Token: token,
		User:  userModel,
	}, nil
}

// Logout handles user logout
// In a JWT-based auth system, logout is handled client-side by removing the token
// This endpoint can be used to perform any server-side cleanup if needed
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// In a JWT system, tokens are stateless so we don't need to do much here
	// In a production system, you might want to implement token blacklisting
	// or use refresh tokens that can be invalidated
	return true, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.AuthResponse, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, name string, username string, password string, email *string, address *string, phone *string) (*model.User, error) {
	// Hash password
	hashedPassword, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return nil, fmt.Errorf("error hashing password: %v", err)
	}

	// Use DB model for persistence
	u := model.UserDB{
		Name:     name,
		Username: username,
		Password: string(hashedPassword),
		IsActive: true,
	}
	if email != nil {
		u.Email = *email
	}
	if address != nil {
		u.Address = *address
	}
	if phone != nil {
		u.Phone = *phone
	}
	if err := r.DB.Create(&u).Error; err != nil {
		return nil, err
	}
	return toGraphQLUser(u), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id int32, name *string, username *string, email *string, address *string, phone *string) (*model.User, error) {
	var u model.UserDB
	err := r.DB.Where("id = ?", id).First(&u).Error
	if err != nil {
		return nil, err
	}

	if name != nil {
		u.Name = *name
	}
	if username != nil {
		u.Username = *username
	}
	if email != nil {
		u.Email = *email
	}
	if address != nil {
		u.Address = *address
	}
	if phone != nil {
		u.Phone = *phone
	}

	if err := r.DB.Save(&u).Error; err != nil {
		return nil, err
	}

	return toGraphQLUser(u), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id int32) (bool, error) {
	var u model.UserDB
	err := r.DB.Where("id = ?", id).First(&u).Error
	if err != nil {
		return false, err
	}

	u.IsActive = false
	if err := r.DB.Save(&u).Error; err != nil {
		return false, err
	}

	if err := r.DB.Delete(&u).Error; err != nil {
		return false, err
	}
	return true, nil
}

// UpdateUserAvatar is the resolver for the updateUserAvatar field.
// Accepts a base64 string and returns the public URL string after saving.
func (r *mutationResolver) UpdateUserAvatar(ctx context.Context, id int32, avatar string) (string, error) {
	var u model.UserDB
	if err := r.DB.Where("id = ?", id).First(&u).Error; err != nil {
		return "", err
	}

	// Ensure upload directory exists
	uploadDir := "uploads/avatars"
	if err := os.MkdirAll(uploadDir, os.ModePerm); err != nil {
		return "", fmt.Errorf("failed to create upload directory: %w", err)
	}

	// If no avatar data was provided, return the current avatar URL
	if avatar == "" {
		return u.Avatar, nil
	}

	// Process the base64 string
	// Remove data:image/...;base64, prefix if present
	base64Data := avatar
	if idx := strings.Index(avatar, "base64,"); idx != -1 {
		base64Data = avatar[idx+7:] // +7 to skip "base64,"
	}

	// Decode base64 string to bytes
	data, err := base64.StdEncoding.DecodeString(base64Data)
	if err != nil {
		return "", fmt.Errorf("invalid base64 data: %w", err)
	}

	// Determine file extension from content type or default to png
	extension := "png"
	if strings.Contains(avatar, "image/jpeg") || strings.Contains(avatar, "image/jpg") {
		extension = "jpg"
	} else if strings.Contains(avatar, "image/gif") {
		extension = "gif"
	}

	// Create unique filename and path
	filename := fmt.Sprintf("%d_%d.%s", id, time.Now().Unix(), extension)
	filePath := filepath.Join(uploadDir, filename)

	// Save file to disk
	if err := os.WriteFile(filePath, data, 0644); err != nil {
		return "", fmt.Errorf("failed to save file: %w", err)
	}

	// Build URL (adjust static serving accordingly)
	fileURL := fmt.Sprintf("/uploads/avatars/%s", filename)

	// Store URL in DB
	u.Avatar = fileURL
	if err := r.DB.Save(&u).Error; err != nil {
		// Try to clean up the file if DB update fails
		os.Remove(filePath)
		return "", fmt.Errorf("failed to update user: %w", err)
	}

	return fileURL, nil
}

// CreateRole is the resolver for the createRole field.
func (r *mutationResolver) CreateRole(ctx context.Context, name string, permissionIds []int32) (*model.Role, error) {
	// Create role and assign permissions in a transaction
	returnValue := &model.Role{}
	err := r.DB.Transaction(func(tx *gorm.DB) error {
		role := model.RoleDB{
			Name:     name,
			IsActive: true,
		}
		if err := tx.Create(&role).Error; err != nil {
			return err
		}
		// Assign permissions
		if len(permissionIds) > 0 {
			rps := make([]model.RolePermissionDB, 0, len(permissionIds))
			for _, pid := range permissionIds {
				rps = append(rps, model.RolePermissionDB{RoleID: int(role.ID), PermissionID: int(pid)})
			}
			if err := tx.Create(&rps).Error; err != nil {
				return err
			}
		}
		// Load permissions to return
		var perms []model.PermissionDB
		if len(permissionIds) > 0 {
			ids := make([]int, 0, len(permissionIds))
			for _, v := range permissionIds {
				ids = append(ids, int(v))
			}
			if err := tx.Where("id IN ?", ids).Find(&perms).Error; err != nil {
				return err
			}
		}
		returnValue = toGraphQLRoleWithPermissions(role, perms)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return returnValue, nil
}

// UpdateRole is the resolver for the updateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id int32, name *string, permissionIds []int32) (*model.Role, error) {
	var out *model.Role
	err := r.DB.Transaction(func(tx *gorm.DB) error {
		var role model.RoleDB
		if err := tx.Where("id = ?", id).First(&role).Error; err != nil {
			return err
		}
		if name != nil {
			role.Name = *name
			if err := tx.Save(&role).Error; err != nil {
				return err
			}
		}
		// Replace permissions: delete existing, then insert new
		if err := tx.Where("role_id = ?", id).Delete(&model.RolePermissionDB{}).Error; err != nil {
			return err
		}
		if len(permissionIds) > 0 {
			rps := make([]model.RolePermissionDB, 0, len(permissionIds))
			for _, pid := range permissionIds {
				rps = append(rps, model.RolePermissionDB{RoleID: int(role.ID), PermissionID: int(pid)})
			}
			if err := tx.Create(&rps).Error; err != nil {
				return err
			}
		}
		// Load permissions for response
		var perms []model.PermissionDB
		if len(permissionIds) > 0 {
			ids := make([]int, 0, len(permissionIds))
			for _, v := range permissionIds {
				ids = append(ids, int(v))
			}
			if err := tx.Where("id IN ?", ids).Find(&perms).Error; err != nil {
				return err
			}
		}
		out = toGraphQLRoleWithPermissions(role, perms)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeleteRole is the resolver for the deleteRole field.
func (r *mutationResolver) DeleteRole(ctx context.Context, id int32) (bool, error) {
	err := r.DB.Transaction(func(tx *gorm.DB) error {
		if err := tx.Where("role_id = ?", id).Delete(&model.RolePermissionDB{}).Error; err != nil {
			return err
		}
		if err := tx.Where("id = ?", id).Delete(&model.RoleDB{}).Error; err != nil {
			return err
		}
		return nil
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, path string) (bool, error) {
	// Basic validation
	if strings.TrimSpace(path) == "" {
		return false, fmt.Errorf("path is required")
	}

	log.Printf("DeleteFile: attempting to delete object at path=%s", path)

	// Delete the file from S3
	err := helpers.DeleteS3ObjectByPath(path)
	if err != nil {
		log.Printf("DeleteFile: deletion failed for path=%s, err=%v", path, err)
		return false, fmt.Errorf("failed to delete file: %v", err)
	}

	log.Printf("DeleteFile: successfully deleted path=%s", path)
	return true, nil
}

// GetUsers is the resolver for the getUsers field.
func (r *queryResolver) GetUsers(ctx context.Context, input *model.PaginationInput) (*model.UserConnection, error) {
	// Base query with role preload
	baseQuery := r.DB.Model(&model.UserDB{}).Preload("Role")

	// Count total
	var totalItems int64
	if err := baseQuery.Count(&totalItems).Error; err != nil {
		return nil, err
	}

	// Apply pagination & sorting via helper
	clientSortWhitelist := map[string]bool{
		"name":       true,
		"created_at": true,
		"updated_at": true,
		"orders":     true,
	}
	var limit, page int32
	baseQuery, limit, page = helpers.ApplyPagination(baseQuery, input, 10, clientSortWhitelist)

	// Execute
	var rows []model.UserDB
	if err := baseQuery.Find(&rows).Error; err != nil {
		return nil, err
	}

	// Collect role IDs from users
	roleIDs := make([]int, 0, len(rows))
	for _, u := range rows {
		roleIDs = append(roleIDs, u.RoleID)
	}

	// Load role permissions in bulk and map roleID -> []PermissionDB
	permByRole := map[int][]model.PermissionDB{}
	if len(roleIDs) > 0 {
		var rps []model.RolePermissionDB
		if err := r.DB.Where("role_id IN ?", roleIDs).Find(&rps).Error; err != nil {
			return nil, err
		}
		permIDsSet := map[int]struct{}{}
		for _, rp := range rps {
			permByRole[rp.RoleID] = append(permByRole[rp.RoleID], model.PermissionDB{ID: rp.PermissionID})
			permIDsSet[rp.PermissionID] = struct{}{}
		}
		if len(permIDsSet) > 0 {
			permIDs := make([]int, 0, len(permIDsSet))
			for id := range permIDsSet {
				permIDs = append(permIDs, id)
			}
			var perms []model.PermissionDB
			if err := r.DB.Where("id IN ?", permIDs).Find(&perms).Error; err != nil {
				return nil, err
			}
			pm := map[int]model.PermissionDB{}
			for _, p := range perms {
				pm[p.ID] = p
			}
			for rid, list := range permByRole {
				full := make([]model.PermissionDB, 0, len(list))
				for _, p := range list {
					if v, ok := pm[p.ID]; ok {
						full = append(full, v)
					}
				}
				permByRole[rid] = full
			}
		}
	}

	// Map users, attaching permissions to role
	items := make([]*model.User, 0, len(rows))
	for _, c := range rows {
		u := toGraphQLUser(c)
		if perms, ok := permByRole[c.RoleID]; ok {
			u.Role = toGraphQLRoleWithPermissions(c.Role, perms)
		} else {
			u.Role = toGraphQLRole(c.Role)
		}
		items = append(items, u)
	}

	// Page info
	pageInfo := helpers.BuildPageInfo(totalItems, limit, page, len(items))

	return &model.UserConnection{
		Items:    items,
		PageInfo: pageInfo,
	}, nil
}

// GetUserDetail is the resolver for the getUserDetail field.
func (r *queryResolver) GetUserDetail(ctx context.Context, id int32) (*model.User, error) {
	var u model.UserDB
	err := r.DB.Where("id = ?", id).Preload("Role").First(&u).Error
	if err != nil {
		if !errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, err
		}
		return nil, nil
	}
	// Load this role's permissions
	var rps []model.RolePermissionDB
	if err := r.DB.Where("role_id = ?", u.RoleID).Find(&rps).Error; err != nil {
		return nil, err
	}
	permIDs := make([]int, 0, len(rps))
	for _, rp := range rps {
		permIDs = append(permIDs, rp.PermissionID)
	}
	var perms []model.PermissionDB
	if len(permIDs) > 0 {
		if err := r.DB.Where("id IN ?", permIDs).Find(&perms).Error; err != nil {
			return nil, err
		}
	}
	out := toGraphQLUser(u)
	out.Role = toGraphQLRoleWithPermissions(u.Role, perms)
	return out, nil
}

// GetRoles is the resolver for the getRoles field.
func (r *queryResolver) GetRoles(ctx context.Context, input *model.PaginationInput) (*model.RoleConnection, error) {
	// Base query
	baseQuery := r.DB.Model(&model.RoleDB{})

	// Count total
	var totalItems int64
	if err := baseQuery.Count(&totalItems).Error; err != nil {
		return nil, err
	}

	// Pagination
	clientSortWhitelist := map[string]bool{
		"name":       true,
		"created_at": true,
		"updated_at": true,
	}
	var limit, page int32
	baseQuery, limit, page = helpers.ApplyPagination(baseQuery, input, 10, clientSortWhitelist)

	// Execute
	var rows []model.RoleDB
	if err := baseQuery.Find(&rows).Error; err != nil {
		return nil, err
	}

	// Collect role IDs
	roleIDs := make([]int, 0, len(rows))
	for _, rdb := range rows {
		roleIDs = append(roleIDs, rdb.ID)
	}

	// Load role permissions in bulk
	permByRole := map[int][]model.PermissionDB{}
	if len(roleIDs) > 0 {
		var rps []model.RolePermissionDB
		if err := r.DB.Where("role_id IN ?", roleIDs).Find(&rps).Error; err != nil {
			return nil, err
		}
		// Collect unique permission IDs
		permIDsSet := map[int]struct{}{}
		for _, rp := range rps {
			permByRole[rp.RoleID] = append(permByRole[rp.RoleID], model.PermissionDB{ID: rp.PermissionID})
			permIDsSet[rp.PermissionID] = struct{}{}
		}
		// Load all permissions
		if len(permIDsSet) > 0 {
			permIDs := make([]int, 0, len(permIDsSet))
			for id := range permIDsSet {
				permIDs = append(permIDs, id)
			}
			var perms []model.PermissionDB
			if err := r.DB.Where("id IN ?", permIDs).Find(&perms).Error; err != nil {
				return nil, err
			}
			// Map by id
			pm := map[int]model.PermissionDB{}
			for _, p := range perms {
				pm[p.ID] = p
			}
			// Replace placeholders with full permission objects
			for rid, list := range permByRole {
				full := make([]model.PermissionDB, 0, len(list))
				for _, p := range list {
					if v, ok := pm[p.ID]; ok {
						full = append(full, v)
					}
				}
				permByRole[rid] = full
			}
		}
	}

	// Map roles
	items := make([]*model.Role, 0, len(rows))
	for _, rdb := range rows {
		perms := permByRole[rdb.ID]
		items = append(items, toGraphQLRoleWithPermissions(rdb, perms))
	}

	pageInfo := helpers.BuildPageInfo(totalItems, limit, page, len(items))
	return &model.RoleConnection{Items: items, PageInfo: pageInfo}, nil
}

// GetRoleDetail is the resolver for the getRoleDetail field.
func (r *queryResolver) GetRoleDetail(ctx context.Context, id int32) (*model.Role, error) {
	var rdb model.RoleDB
	if err := r.DB.Where("id = ?", id).First(&rdb).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, nil
		}
		return nil, err
	}
	// Load permissions
	var rps []model.RolePermissionDB
	if err := r.DB.Where("role_id = ?", id).Find(&rps).Error; err != nil {
		return nil, err
	}
	permIDs := make([]int, 0, len(rps))
	for _, rp := range rps {
		permIDs = append(permIDs, rp.PermissionID)
	}
	var perms []model.PermissionDB
	if len(permIDs) > 0 {
		if err := r.DB.Where("id IN ?", permIDs).Find(&perms).Error; err != nil {
			return nil, err
		}
	}
	return toGraphQLRoleWithPermissions(rdb, perms), nil
}

// GetPermissions is the resolver for the getPermissions field.
func (r *queryResolver) GetPermissions(ctx context.Context) ([]*model.Permission, error) {
	var rows []model.PermissionDB
	if err := r.DB.Find(&rows).Error; err != nil {
		return nil, err
	}
	items := make([]*model.Permission, 0, len(rows))
	for _, p := range rows {
		items = append(items, toGraphQLPermission(p))
	}
	return items, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
