// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Auditable interface {
	IsAuditable()
	GetIsActive() bool
	GetDeletedAt() *time.Time
	GetCreatedAt() time.Time
	GetUpdatedAt() time.Time
}

type Mutation struct {
}

type PageInfo struct {
	CurrentPage     int32  `json:"current_page"`
	PerPage         int32  `json:"per_page"`
	TotalItems      int32  `json:"total_items"`
	TotalPages      int32  `json:"total_pages"`
	HasNextPage     bool   `json:"has_next_page"`
	HasPreviousPage bool   `json:"has_previous_page"`
	StartItem       *int32 `json:"start_item,omitempty"`
	EndItem         *int32 `json:"end_item,omitempty"`
}

type PaginationInput struct {
	Limit  *int32  `json:"limit,omitempty"`
	Page   *int32  `json:"page,omitempty"`
	SortBy *string `json:"sortBy,omitempty"`
}

type Permission struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Query struct {
}

type Role struct {
	ID          int32         `json:"id"`
	Name        string        `json:"name"`
	Permissions []*Permission `json:"permissions"`
	IsActive    bool          `json:"is_active"`
	DeletedAt   *time.Time    `json:"deleted_at,omitempty"`
	CreatedAt   time.Time     `json:"created_at"`
	UpdatedAt   time.Time     `json:"updated_at"`
}

func (Role) IsAuditable()                  {}
func (this Role) GetIsActive() bool        { return this.IsActive }
func (this Role) GetDeletedAt() *time.Time { return this.DeletedAt }
func (this Role) GetCreatedAt() time.Time  { return this.CreatedAt }
func (this Role) GetUpdatedAt() time.Time  { return this.UpdatedAt }

type RoleConnection struct {
	Items    []*Role   `json:"items"`
	PageInfo *PageInfo `json:"page_info"`
}

type RolePermission struct {
	RoleID       int32 `json:"role_id"`
	PermissionID int32 `json:"permission_id"`
}

type User struct {
	ID        int32      `json:"id"`
	Name      string     `json:"name"`
	Username  string     `json:"username"`
	Email     *string    `json:"email,omitempty"`
	Address   *string    `json:"address,omitempty"`
	Phone     *string    `json:"phone,omitempty"`
	Avatar    *string    `json:"avatar,omitempty"`
	RoleID    int32      `json:"role_id"`
	Role      *Role      `json:"role"`
	IsActive  bool       `json:"is_active"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

func (User) IsAuditable()                  {}
func (this User) GetIsActive() bool        { return this.IsActive }
func (this User) GetDeletedAt() *time.Time { return this.DeletedAt }
func (this User) GetCreatedAt() time.Time  { return this.CreatedAt }
func (this User) GetUpdatedAt() time.Time  { return this.UpdatedAt }

type UserConnection struct {
	Items    []*User   `json:"items"`
	PageInfo *PageInfo `json:"page_info"`
}
